### ISSUE TITLE
Use tailwindcss to remove all `StyleSheet.create` declarations

### ISSUE THREAD

**Issue by subramanian-elavathur** [kalpadhwaryu/newsnap#2]
Use https://github.com/vadimdemedes/tailwind-rn to integrate https://tailwindcss.com/ into your project and remove all `StyleSheet.create` declarations

**Comment by kalpadhwaryu** [comment]
Have removed all StyleSheet.create declarations and added Tailwind to the whole Project. [Link to commit](https://github.com/kalpadhwaryu/newsnap/commit/82908f7521b4e7fcfc7f2fc498ac34f4e365ac31)
